package view.components;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.StudentAccount;
import utils.StudentAccountDAO;
import utils.StudentAccountManagement;
import view.main.Main;
import view.main.Main2;

public class PanelLoginAndRegister extends javax.swing.JLayeredPane {

    public PanelLoginAndRegister() {
        initComponents();
        login.setVisible(false);
        register.setVisible(true);
        images();
        userNameAccountLoginTF.setHint("Username");
        passwordLoginTF.setHint("Password");
    }

    private ImageIcon scaleImage(String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        return scaledIcon;
    }

    public void showRegister(boolean show) {
        if (show) {
            register.setVisible(true);
            login.setVisible(false);
        } else {
            register.setVisible(false);
            login.setVisible(true);
        }
    }

    private void images() {
        userLabel.setIcon(scaleImage("src/view/images/user.png"));
        showPassLabel.setIcon(scaleImage("src/view/images/show.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel1 = new javax.swing.JLabel();
        passwordLB1 = new javax.swing.JLabel();
        fogotLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        showPassLabel = new javax.swing.JLabel();
        signInButton1 = new view.swing.Button();
        userNameAccountLoginTF = new view.swing.MyTextField();
        passwordLoginTF = new view.swing.MyPasswordField();
        register = new javax.swing.JPanel();
        createAccLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passwordLB = new javax.swing.JLabel();
        nameAccountTF = new view.swing.MyTextField();
        userNameAccount = new view.swing.MyTextField();
        passwordField = new view.swing.MyPasswordField();
        signUpButton = new view.swing.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Sign in");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, 60));

        usernameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(0, 102, 102));
        usernameLabel1.setText("User Name");
        login.add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        passwordLB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLB1.setForeground(new java.awt.Color(0, 102, 102));
        passwordLB1.setText("Password");
        login.add(passwordLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        fogotLabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        fogotLabel.setText("Forgot your password?");
        login.add(fogotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 170, -1));

        userLabel.setPreferredSize(new java.awt.Dimension(30, 30));
        login.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 30, 30));

        showPassLabel.setPreferredSize(new java.awt.Dimension(30, 30));
        showPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPassLabelMousePressed(evt);
            }
        });
        login.add(showPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 40, 30));

        signInButton1.setBackground(new java.awt.Color(0, 102, 102));
        signInButton1.setForeground(new java.awt.Color(255, 255, 255));
        signInButton1.setText("SIGN IN");
        signInButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButton1ActionPerformed(evt);
            }
        });
        login.add(signInButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 50));

        userNameAccountLoginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameAccountLoginTFActionPerformed(evt);
            }
        });
        login.add(userNameAccountLoginTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 330, 40));

        passwordLoginTF.setToolTipText("");
        passwordLoginTF.setEchoChar('\u25cf');
        login.add(passwordLoginTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 330, -1));

        add(login, "card3");

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAccLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        createAccLabel.setForeground(new java.awt.Color(0, 102, 102));
        createAccLabel.setText("Create Account");
        register.add(createAccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 270, 58));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 102, 102));
        usernameLabel.setText("User Name");
        register.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 102));
        nameLabel.setText("Name");
        register.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        passwordLB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLB.setForeground(new java.awt.Color(0, 102, 102));
        passwordLB.setText("Password");
        register.add(passwordLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        nameAccountTF.setHint("Name");
        register.add(nameAccountTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 290, -1));

        userNameAccount.setHint("Username");
        register.add(userNameAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 290, -1));

        passwordField.setHint("Password");
        passwordField.setEchoChar('\u25cf');
        register.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 290, -1));

        signUpButton.setBackground(new java.awt.Color(0, 102, 102));
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("SIGN UP");
        signUpButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        register.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 140, 50));

        add(register, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private boolean check = false;

    private void showPassLabelMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_showPassLabelMousePressed
        if (!check) {
            passwordLoginTF.setEchoChar((char) 0);
            showPassLabel.setIcon(scaleImage("src/view/images/hide.png"));
            check = true;

        } else {
            check = false;
            passwordLoginTF.setEchoChar('\u25cf');
            showPassLabel.setIcon(scaleImage("src/view/images/show.png"));
        }
    }// GEN-LAST:event_showPassLabelMousePressed

    private void signInButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signInButton1ActionPerformed
        String userName = userNameAccountLoginTF.getText();
        String password = passwordLoginTF.getText();
        ArrayList<StudentAccount> list = StudentAccountDAO.restoreListFromFile("CSE_305_Final\\CSE_305_FINAL\\src");
        if (userName.length() == 0 || password.length() == 0) {
            JOptionPane.showMessageDialog(nameAccountTF, "Please enter your account information");
            return;
        }
        for (StudentAccount e : list) {
            if (e.getUsername().equals(userName)) {
                if (e.getPassword().equals(password)) {
                    Main2 main2 = new Main2();

                    main2.account = new StudentAccount(e.getName(), e.getUsername(), e.getPassword(), e.getIrn(),
                            e.getGender(), e.getExpense());
                    main2.listOfStudentAccount = list;
                    JOptionPane.showMessageDialog(nameAccountTF, "Welcome!!!");
                    main2.setVisible(true);
                    Main.shutdown();
                    return;
                }
            }

        }
        JOptionPane.showMessageDialog(nameAccountTF, "Username or password is incorrect");
    }// GEN-LAST:event_signInButton1ActionPerformed

    private void userNameAccountLoginTFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userNameAccountLoginTFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userNameAccountLoginTFActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signUpButtonActionPerformed
        String name = nameAccountTF.getText();
        String username = userNameAccount.getText();
        String password = passwordField.getText();
        if (name.length() == 0 || username.length() == 0 || password.length() == 0) {
            JOptionPane.showMessageDialog(nameAccountTF, "Please enter full information!");
            return;
        }

        // ArrayList<StudentAccount> list =
        // StudentAccountDAO.restoreListFromFile("CSE_305_Final\\CSE_305_FINAL\\src");

        // for (StudentAccount e : list) {
        // if (e.getName().equals(name)) {
        // JOptionPane.showMessageDialog(nameAccountTF, "Your username has already
        // exist!");
        // userNameAccount.setText("");
        // return;
        // }
        // }
        if (StudentAccountManagement.isAccountExisted(username)) {
            JOptionPane.showMessageDialog(nameAccountTF, "Your username has already exist!");
            userNameAccount.setText("");
            return;
        }
        StudentAccount newAccount = new StudentAccount(name, username, password, "N/a", "N/a", 0.0);
        StudentAccountDAO.saveAccountAsChar(newAccount, "CSE_305_Final\\CSE_305_FINAL\\src");
        JOptionPane.showMessageDialog(nameAccountTF, "Register successfully!");
        nameAccountTF.setText("");
        userNameAccount.setText("");
        passwordField.setText("");
    }// GEN-LAST:event_signUpButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccLabel;
    private javax.swing.JLabel fogotLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel login;
    private view.swing.MyTextField nameAccountTF;
    private javax.swing.JLabel nameLabel;
    private view.swing.MyPasswordField passwordField;
    private javax.swing.JLabel passwordLB;
    private javax.swing.JLabel passwordLB1;
    private view.swing.MyPasswordField passwordLoginTF;
    private javax.swing.JPanel register;
    private javax.swing.JLabel showPassLabel;
    private view.swing.Button signInButton1;
    private view.swing.Button signUpButton;
    private javax.swing.JLabel userLabel;
    private view.swing.MyTextField userNameAccount;
    private view.swing.MyTextField userNameAccountLoginTF;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables

}
