package view.component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.ImageIcon;

public class PanelCover extends javax.swing.JPanel {

    private ActionListener event;
    private boolean isLogin;
    private final DecimalFormat df = new DecimalFormat("##0.###", DecimalFormatSymbols.getInstance().getInstance(Locale.US));

    public PanelCover() {
        initComponents();
        setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        oneLabel = new javax.swing.JLabel();
        twoLabel = new javax.swing.JLabel();
        threeLabel = new javax.swing.JLabel();
        oneLabel1 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        oneLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        oneLabel.setForeground(new java.awt.Color(255, 255, 255));
        oneLabel.setText("Welcome Back");
        add(oneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 50));

        twoLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        twoLabel.setForeground(new java.awt.Color(255, 255, 255));
        twoLabel.setText("To keep connected with us ");
        add(twoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 20));

        threeLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        threeLabel.setForeground(new java.awt.Color(255, 255, 255));
        threeLabel.setText("please login with your personal info");
        add(threeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 260, -1));

        oneLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        oneLabel1.setForeground(new java.awt.Color(255, 255, 255));
        oneLabel1.setText("to BUS SERVICE");
        add(oneLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        event.actionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        GradientPaint gra = new GradientPaint(0, 0, Color.decode("#000000"), 0, getHeight(), Color.decode("#0f9b0f"));
        g2.setPaint(gra);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(g);
    }

    public void addEvent(ActionListener e) {
        this.event = e;
    }

    public void registerLeft(double v) {
        v = Double.valueOf(df.format(v));
        login(false);

    }

    public void registerRight(double v) {
        v = Double.valueOf(df.format(v));
        login(false);

    }

    public void loginLeft(double v) {
        v = Double.valueOf(df.format(v));
        login(true);
    }

    public void loginRight(double v) {
        v = Double.valueOf(df.format(v));
        login(true);

    }

    public void login(boolean login) {
        if (this.isLogin != login) {
            if (login) {
                oneLabel.setText("Hi there!");
                oneLabel1.setText("Keep going on by");

                twoLabel.setText("Enter your personal details");
                threeLabel.setText("and start your journey with us");
                jButton1.setText("SIGN UP");
            } else {
                oneLabel.setText("Welcome Back!");
                oneLabel1.setText("to BUS SERVICE");
                twoLabel.setText("To keep connected with us ");
                threeLabel.setText("please login with your personal info");
                jButton1.setText("SIGN IN");
            }
            this.isLogin = login;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel oneLabel;
    private javax.swing.JLabel oneLabel1;
    private javax.swing.JLabel threeLabel;
    private javax.swing.JLabel twoLabel;
    // End of variables declaration//GEN-END:variables
}
